# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170106_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobssubmitted',
            name='name',
        ),
        migrations.AddField(
            model_name='jobssubmitted',
            name='first_name',
            field=models.CharField(default='John', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobssubmitted',
            name='last_name',
            field=models.CharField(default='Doe', max_length=80),
            preserve_default=False,
        ),
    ]
